### ISSUE TITLE
Change Language Model

### ISSUE THREAD

**Issue by dtronicsuk** [vodkabydlo/GPT-Twitch-Chatbot#3]
Hey

Is there any way of changing the Language model used?

**Comment by irisrumtub** [comment]
Hi @dtronicsuk, thank you for reaching out! 
You mean something instead of davinci-003? Or language that model speaks to you in? In latter case, you can talk to it in any language you wish. 
In case If you want something besides davinci, I can make a feature which will allow you to switch between different models. If you would want such a feature then I am ready to do it easily.

By the way I have a bot on the dedicated server that is currently deployed and listens for twitch channels 24/7. I am testing things to launch large scale bot. I am currently looking for streamers to join testing. If you wish to participate(100% free for everyone who participate in testing and after that), then I would be glad to invite you, whatever your numbers of viewers and followers are. I'd you are interested yo can contact me at
tvburis@gmail.com
Or 
irisrumtub#7359 discord
Or
@irisrumtub telegram

**Comment by dtronicsuk** [comment]
Ok, i have just added you on discord :D

**Comment by irisrumtub** [comment]
closing the issue
